
import React from 'react';
import { Shield, Zap, BrainCircuit, FileText, Share2, Bell, Terminal, Lock } from 'lucide-react';

export const Features: React.FC = () => {
  const features = [
    {
      icon: <Shield className="h-6 w-6 text-white" />,
      title: 'Advanced Vulnerability Detection',
      description: 'Identify security vulnerabilities in your code before they become threats. Our scanner detects SQL injection, XSS, CSRF, and more.',
      bgClass: 'bg-scanner-blue-600 dark:bg-scanner-blue-500',
    },
    {
      icon: <BrainCircuit className="h-6 w-6 text-white" />,
      title: 'AI-Powered Remediation',
      description: 'Get intelligent fix suggestions generated by our advanced AI model. Each vulnerability comes with contextual code solutions.',
      bgClass: 'bg-scanner-blue-700 dark:bg-scanner-blue-600',
    },
    {
      icon: <Zap className="h-6 w-6 text-white" />,
      title: 'Real-time Analysis',
      description: 'Experience blazing-fast scanning that provides immediate results without sacrificing accuracy or thoroughness.',
      bgClass: 'bg-scanner-blue-600 dark:bg-scanner-blue-500',
    },
    {
      icon: <Terminal className="h-6 w-6 text-white" />,
      title: 'Multiple Language Support',
      description: 'Analyze code written in JavaScript, Python, Java, Go, Ruby, PHP, and more with language-specific vulnerability detection.',
      bgClass: 'bg-scanner-blue-700 dark:bg-scanner-blue-600',
    },
    {
      icon: <FileText className="h-6 w-6 text-white" />,
      title: 'Comprehensive Reports',
      description: 'Generate detailed security reports that highlight vulnerabilities, their severity, and recommended fixes for your team.',
      bgClass: 'bg-scanner-blue-600 dark:bg-scanner-blue-500',
    },
    {
      icon: <Share2 className="h-6 w-6 text-white" />,
      title: 'Easy Sharing',
      description: 'Share scan results and reports with team members via a secure link or export them in various formats.',
      bgClass: 'bg-scanner-blue-700 dark:bg-scanner-blue-600',
    },
    {
      icon: <Bell className="h-6 w-6 text-white" />,
      title: 'Security Alerts',
      description: 'Stay informed about critical vulnerabilities with customizable alerts and notifications for your codebase.',
      bgClass: 'bg-scanner-blue-600 dark:bg-scanner-blue-500',
    },
    {
      icon: <Lock className="h-6 w-6 text-white" />,
      title: 'Private & Secure',
      description: 'Your code never leaves your browser. All scanning is done locally to ensure maximum privacy and security.',
      bgClass: 'bg-scanner-blue-700 dark:bg-scanner-blue-600',
    },
  ];

  return (
    <section id="features" className="py-20 bg-slate-50 dark:bg-slate-900">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-16">
          <h2 className="text-3xl font-bold tracking-tight text-slate-900 dark:text-white sm:text-4xl">
            Powerful Security Features
          </h2>
          <p className="mt-4 max-w-2xl mx-auto text-lg text-slate-600 dark:text-slate-300">
            SHADOWSCAN combines advanced AI with security expertise to deliver exceptional vulnerability detection and remediation.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          {features.map((feature, index) => (
            <div 
              key={index} 
              className="bg-white dark:bg-slate-800 rounded-2xl shadow-card hover:shadow-lg transition-all duration-300 overflow-hidden animate-fade-in"
              style={{ animationDelay: `${index * 0.1}s` }}
            >
              <div className={`${feature.bgClass} p-4 flex justify-center`}>
                <div className="rounded-full p-2 bg-white/20">
                  {feature.icon}
                </div>
              </div>
              <div className="p-6">
                <h3 className="text-lg font-semibold text-slate-900 dark:text-white mb-2">{feature.title}</h3>
                <p className="text-slate-600 dark:text-slate-300 text-sm">{feature.description}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};
